name: CD Pipeline

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull rajendra0968/html-project:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 81:81 --name cicd-pipeline-container rajendra0968/html-project
